### ISSUE TITLE
Merging edgemincyclebasis into Graphs.jl

### ISSUE THREAD

**Issue by antonhinneck** [mojaie/MolecularGraph.jl#101]
Hi, I recently found an [Issue](https://github.com/JuliaGraphs/Graphs.jl/issues/219) concerning min-weight cycle bases in Graphs.jl and saw that you implement a function like this in your repository that is already compatible with Graphs.

Would it be possible for you to merge it into Graphs.jl?
Graphs.jl only implements an algorithm for A cycle_basis, that is not necessarily minimum-weight.

**Comment by mojaie** [comment]
Thank you for contacting me and I apologize for very late reply.
I will make post to the original issue.
