### ISSUE TITLE
sdfilereader include associated data items

### ISSUE THREAD

**Issue by timoleistner** [mojaie/MolecularGraph.jl#106]
It would be nice to use one of SDFiles key features and include the associated data to the molfile.
More often than not, some internal ID or molecular properties are also included in the [SDFile](https://en.wikipedia.org/wiki/Chemical_table_file#SDF).
Could be as simple as including a properties dict to the MolGraph struct and parsing the associated data items into this.

**Comment by timoleistner** [comment]
just noticed there is `metadata()` which does exactly what I want. It's not in the docs but in the corresponding "how to use" pluto notebooks.

**Comment by mojaie** [comment]
Thank you very much for the comment. Yes, this should be documented.
Please note that `metadata` is still incomplete and may not work with SMILES, and the interface would change.
