### ISSUE TITLE
Bug with rem_vertex! with next-to-edge atoms

### ISSUE THREAD

**Issue by pw0908** [mojaie/MolecularGraph.jl#113]
Hi!
Thank you so much for building this package! It's helped a lot with our ability to process molecular structures. 

I just wanted to report an issue I've noticed with `rem_vertex!` when you remove an atom next to the final atom of a molecule. For example, in hexanol, if you try to remove the carbon next to the oxygen:
```julia
mol = smilestomol("CCCCCCO")
rem_vertex!(mol, 6) # KeyError: key Edge 6 => 7 not found
```
I believe that this is due to how the final vertex is treated in MolecularGraph:
https://github.com/mojaie/MolecularGraph.jl/blob/fb4bb8187e4287272c0633517e5304c845f8d440/src/model/molgraph.jl#L191-L192

If this re-indexing is done, then this edge will no longer exist. 

I'm not quite sure what the fix will be....

**Comment by mojaie** [comment]
Thank you for catching. I will merge your PR soon.
