### ISSUE TITLE
Bond length

### ISSUE THREAD

**Issue by Nick-Mul** [mojaie/MolecularGraph.jl#115]
Hi, I was wondering if you could give some tips on how to calculate bond length assuming I had coordinates on the atoms? 
I really apricate the work you've put into this.
Best regards,
Nick

**Comment by mojaie** [comment]
Thank you very much.
There may be some kind of bond length:

1. Actual bond length (e.g. 1.54 angstroms for C-C)
1. Bond length in SDFile coordinate system (2D or 3D)
1. Bond length in SVG/PNG image

Which do you mean?

**Comment by Nick-Mul** [comment]
Thanks for reply, sorry I wasn't clear. I have an accurate structure from QM which I have turned into a sdf, so type 2.

**Comment by mojaie** [comment]
Bond length in SDFile depends on the implementation of SDFile provider (drawing software or coordinate generator).
Here is the case of coordgenlibs used by MolecularGraph.jl

```jl
using MolecularGraph
mol = smilestomol("CCC")
distance(coordgen(mol)[1][1:2, :])
```

output
```
49.99717646641916
```

**Comment by mojaie** [comment]
There is no distance function for Atom. A workaround is
```jl
a = SDFAtom(:H, 0, 1, nothing, [-5.2539, -1.5578, 3.2749])
b = SDFAtom(:C, 0, 1, nothing, [-4.93, -1.6748, -0.0976])
distance(Point3D(a.coords), Point3D(b.coords))
```

`distance` simply calls `(v, u) -> norm(v - u)` where v and u are vectors of the same length.

Note that geometry APIs (in `src/geometry`) is not stable and would be moved to [GeometryBasics.jl](https://github.com/JuliaGeometry/GeometryBasics.jl) in the future. So the following would be better:

```jl
using LinearAlgebra
a = SDFAtom(:H, 0, 1, nothing, [-5.2539, -1.5578, 3.2749])
b = SDFAtom(:C, 0, 1, nothing, [-4.93, -1.6748, -0.0976])
norm(a.coords - b.coords)
```

**Comment by Nick-Mul** [comment]
I see that, thanks for that. If I could be trouble you for a one more questions.

What's the best way to access the source and target nodes in the bonds, is it through the mol.eprops.:keys ?

**Comment by mojaie** [comment]
see https://github.com/JuliaGraphs/Graphs.jl
If you came from NetworkX, you may feel that the design of Graphs.jl is a bit wired.

```julia-repl
julia> using Graphs, MolecularGraph
julia> mol = smilestomol("CCC")
{3, 2} simple molecular graph SMILESMolGraph
julia> e = iterate(edges(mol))[1]
Edge 1 => 2
julia> get_prop(mol, e, :order)
1
julia> src(e)
1
julia> dst(e)
2
julia> get_prop(mol, 2, :symbol)
:C
```

**Comment by Nick-Mul** [comment]
Thanks for pointers, much appreciated.
