### ISSUE TITLE
Save SVG to files. 

### ISSUE THREAD

**Issue by Kelvyn88** [mojaie/MolecularGraph.jl#13]
Hi, its me again. This package is really amazing. I want to integrate some features to a very large program written with Gtk.jl. The output of display("image/svg+xml",  mol_svg) only works under web browser. I tried using SvgCanvas into Gtk but it fails. 

The easiest way at the moment is to save the drawsvg output (string) to a svg (or others image formats) to a file, and then attached to a GtkImage or Canvas. 

Do you know how to export the output of drawsvg yo a file?

Thanks again.

**Comment by mojaie** [comment]
`drawsvg` just returns SVG text, so the easiest way is,

```julia
write(open("your_img_dir/output.svg", "w"), drawsvg(mol_svg, 300, 300))
```

**Comment by Kelvyn88** [comment]
The code actually runs but the file has 0 kb.  

When openning the svg file in the browser shows the next line:

This XML file does not appear to have any style information associated with it. The document tree is shown below.

**Comment by mojaie** [comment]
Please check the output.
```
mol = sdftomol(sdf_path)
println(atomcount(mol))
```
Is your molecule correctly parsed?

```
svg_string = drawsvg(mol, 300, 300)
println(svg_string)
```
Does the string have SVG contents?
Then,

```
write(open("your_img_dir/output.svg", "w"), svg_string)
```

**Comment by Kelvyn88** [comment]
Still not working. All the previous steps are ok but the last one generates an output: 2962. It creates the svg file with no content (0 kb). I´m on Win10 by the way, and using the lastest smilestomol function. 

sorry for the delay (Mexico).

Thanks

**Comment by mojaie** [comment]
Sorry, I forgot that `close`ing the file is necessary (See the document `Base.open`).
https://docs.julialang.org/en/v1/base/io-network/#Base.open

```
io = open("your_img_dir/output.svg", "w")
write(io, svg_string)
close(io)
```

or

```
open("your_img_dir/output.svg", "w") do
    write(io, svg_string)
end
```

would work.

**Comment by Kelvyn88** [comment]
woww Thanks!! 

I really appreciate your help.

Kelvyn
