### ISSUE TITLE
Topics and destructive changes in v0.6.0

### ISSUE THREAD

**Issue by mojaie** [mojaie/MolecularGraph.jl#14]
Topics of next version (v0.6.0)
- Improve atomic valence definition (especially for the case of BH4+) 07899dc
- Improve definition of `pielectron` and add `hybridization` vector acb74bf
- Add `molecularformula` and `empiricalformula` da278f3
- Refer NIST standard atomic weight table for molecular mass calculation
- Calculated exact mass and simulated mass spectrum

Destructive changes
- some preprocessing methods are renamed (src/preprocess.jl)
- `stdweight` was renamed to `standardweight` and moved to src/mass.jl
- `atomname` (returns full atom name) is no longer available

**Comment by mojaie** [comment]
I'm working on direct C interfacing with coordgenlibs.
The next version will no longer require Cxx.jl, so it may be compatible with Julia <= 1.4.

**Comment by Kelvyn88** [comment]
Great for the Cxx issue.

**Comment by Kelvyn88** [comment]
Working perfect under julia 1.4.1. Thanks
