### ISSUE TITLE
Information about simulatemassspec

### ISSUE THREAD

**Issue by Kelvyn88** [mojaie/MolecularGraph.jl#15]
Hi,

Could you provide more information related to the function simulatemasspec?

- Method or paper

- If I change the functional groups, the function still can simulate?

Thanks in advance.

**Comment by mojaie** [comment]
Here is the notebook tutorial.
https://nbviewer.jupyter.org/github/mojaie/MolecularGraph.jl_notebook/blob/master/notebook/massAndIsotopes.ipynb

Functional group related features and mass calculation features are totally independent. They never interact each other.

**Comment by Kelvyn88** [comment]
Thanks @mojaie 

Coudl you provide more scientific background related simulatemasspec?

Thanks in advance. 

Kelvyn

**Comment by mojaie** [comment]
Mass spec. simulation is based on only isotopic composition of molecules. It is just as the same as many mass spec. related software packages do. What kind of background information do you need?

**Comment by Kelvyn88** [comment]
Thanks! That was the answer I was looking for.


Kelvyn
