### ISSUE TITLE
default preprocessing

### ISSUE THREAD

**Issue by mojaie** [mojaie/MolecularGraph.jl#20]
- kekulize (for SMILES)
- setdiastereo
- setstereocenter

are necessary for most of molecular graph operations, less computational cost and important for format compatibility (SMILES <-> SDFile), so `smilestomol()`, `sdftomol()` and related methods should run those above.

**Comment by mojaie** [comment]
Done 0d84cb7

**Comment by richardskim111** [comment]
Can they be passed in as boolean optional parameters to `smilestomol()` and `sdftomol()`?  For instance, 

```julia
function smilestomol(smiles::AbstractString; kekulize::Bool=true, setdiastereo::Bool=true)
    mol = parse(SMILES, smiles)
    if kekulize
       kekulize!(mol)
    end
    if setdiastereo
       setdiastereo!(mol)
    end
    return mol
end
```
I'm finding many of my existing smiles failing since the update.  I don't know if there is an issue with `kekulize!`.  I see no problem in rdkit though...

**Comment by mojaie** [comment]
If you don't want to use preprocess methods, just call `parse(SMILES, smiles)` and do custom preprocessing . Please note that SMILES molecule without kekulization may have wrong valence and implicit hydrogens. 

Please check which SMILES strings have failed with `kekulize!`.
Following tutorial would be helpful:
https://nbviewer.jupyter.org/github/mojaie/MolecularGraph.jl_notebook/blob/master/notebook/preprocess.ipynb
