### ISSUE TITLE
structure image grid

### ISSUE THREAD

**Issue by mojaie** [mojaie/MolecularGraph.jl#24]
like RDKit's `Draw.MolsToGridImage`

**Comment by richardskim111** [comment]
This seems easy enough to be a good first contribution.  Can I give it a try?

**Comment by mojaie** [comment]
Thank you very much. I'm happy if you contribute.
We have no contribution guidelines yet, but you can do it as like other OSS projects.

**Comment by mojaie** [comment]
Implemented in 1b2e6b77d9579fa918cfcc94459cbec6d3347b3f
`html_grid(svgs, cols, rowheight)` generates HTML codes to show SVGs in grid layout with given number of columns and row height. See notebook tutorial https://mojaie.github.io/MolecularGraph.jl_notebook/drawing_molecule.jl.html
