### ISSUE TITLE
Notebook Smiles not working

### ISSUE THREAD

**Issue by Kelvyn88** [mojaie/MolecularGraph.jl#3]
Hi, first to all, this package looks amazing!!! Great work!

The Notebook Smiles is not working for me. The problem is in the function drawsvg!:

`UndefVarError: drawsvg! not defined`

I am running Julia 1.3.1 on Win10 x64.

**Comment by Kelvyn88** [comment]
Another problem presented is in display function. 

This code comes from the notebook mcs (basic example), 

`display("text/html", displayimgpair(svg1, svg2))`

ERROR: MethodError: no method matching show(::Base.TTY, ::MIME{Symbol("text/html")}, ::String)

**Comment by mojaie** [comment]
Thank you for reaching out to the repository!

1. `drawsvg!` was removed, and `drawsvg` is available now.
So `mol_svg = drawsvg(mol, 200, 200)` may work.
Thank you for catching it.

2. `displayimgpair` is defined in the notebook for demo (see the first code block).
It just calls two structure image SVG strings generated by `drawsvg`.

I think Gtk can load SVG image. Or do you want to manipulate the image interactively with GUI?
Only SVG canvas is available now, but, in the future, other GUI kits like Gtk (Cairo), Qt, HTML5 canvas and also MatPlotLib can be implemented by interfacing `Canvas` type (see ./src/draw/ directory). Hopefully I will add instruction for structure drawing interfaces.

**Comment by mojaie** [comment]
Unfortunately `drawsvg` does not work with SMILES molecules because 2D coords generation is not available now.

It is very tough task, so I'm going to make an interface to external libraries like Schrodinger's coordgenlibs. A workaround for now is to build molecules from SDFile or generate coordinates by using 2D coords generators directly.

**Comment by Kelvyn88** [comment]
Thanks. Please let me know once the SMILES works for 2D coord generation. 

I will fork your package and update the functional groups to a very recent paper. Then if you are interested I will make a pull request. 

Thanks again! Very amazing package.

**Comment by mojaie** [comment]
Thank you very much.
I recommend you make your own functional group file in `assets/funcgroup` folder. Functional group definition file (.yml) in the folder will be automatically loaded when this package is loaded.

**Comment by mojaie** [comment]
@Kelvyn88 new version 0.4.0 have 2D coords generation by using Schrodinger's coordgenlibs. Molecules created by `smilestomol` already have 2D coords information. Please try it.

**Comment by Kelvyn88** [comment]
Thanks @mojaie let me try it.

**Comment by Kelvyn88** [comment]
@mojaie It works!! Thanks!. Very few differents in the image representation of the molecule but everything is working now. Thanks again!.
