### ISSUE TITLE
Duplicate detection in functional groups

### ISSUE THREAD

**Issue by Kelvyn88** [mojaie/MolecularGraph.jl#31]
Hi @mojaie 

I have the following molecule:
![image](https://user-images.githubusercontent.com/11316335/89974949-18247100-dc2a-11ea-99c5-bafbc72777c0.png)

I need to identify the groups: "CH2" and "CH2N":

- key "CH2"
  query: "[CH2]"

- key: "CH2N"
  have: ["CH2"]
  query: "[CH2][N]"

The analysis identified [2][4] for CH2, then with the largestcomponents, [3,4] [2,3] for CH2N, but this counts by duplicate the Nitrogen [3]. It should identify [4] for CH2 and [2,3] for CH2N. 

Any suggestion or comment will be greatly appreciated.

**Comment by mojaie** [comment]
Your task seems to be in the field of matching problem.
https://en.wikipedia.org/wiki/Matching_(graph_theory)

Or simple fragmentation approach like Matched Molecule Pair may work for this kind of application.

**Comment by Kelvyn88** [comment]
Thanks @mojaie 

I'll write a code to compare to sets, all the groups identified and the simplified with largestcomponents. If the code identify duplicacion in the simplified set, it'll substitute by the available in the first sets. Its a overall idea. 

Thanks.
