### ISSUE TITLE
largestcomponent comment

### ISSUE THREAD

**Issue by Kelvyn88** [mojaie/MolecularGraph.jl#34]
Hi to all

I was working in writting some functional groups and I noticed this:

To identify largest components, the simply ones should be define first (.yaml file) to proper identification. 

Thanks

**Comment by mojaie** [comment]
Thank you for sharing your feedback!
Maybe it is not I intended. It is true that functional group search is done by the order that defined in the .yaml file, but sub/superset relationship should be determined by the ontology graph regardless of .yaml file order.
I'd be happy if you provide example code of your case.

**Comment by Kelvyn88** [comment]
Sure, it is a very short example. Let's try to identify the following molecule:

`"S(SC)C"`

![image](https://user-images.githubusercontent.com/11316335/98592937-0e95be00-2298-11eb-8afa-15c4d073cbda.png)

with the following order list for functional groups:

```
# 1
- key: "CH3"
  query: "[CH3D1;!R]"

# 143
- key: "CH3S"
  have: ["-S-", "CH3"]
  query: "[CH3;!R][#16;!R]"

# 185
- key: "-S-"
  query: "[SX2]"
```

The results is only CH3 and -S-. If I reorder the groups to first define the simpliest molecules as:

```
# 1
- key: "CH3"
  query: "[CH3D1;!R]"

# 185
- key: "-S-"
  query: "[SX2]"

# 143
- key: "CH3S"
  have: ["-S-", "CH3"]
  query: "[CH3;!R][#16;!R]"
```

The results iis CH3, -S- and CH3S for all groups, and largestcomponents yields CH3S, the correct identification. 


Thanks
Kelvyn

**Comment by mojaie** [comment]
Thank you for providing the example.
I checked the module, and found some codes that should be fixed.
The workaround is to order the queries as you did.

**Comment by Kelvyn88** [comment]
Thanks @mojaie 

Another issue related to the same topic.  With the molecule:

![image](https://user-images.githubusercontent.com/11316335/98631415-00b95a80-22e3-11eb-9c1f-d4f9e1468432.png)

by using the same functional groups as above: 

![image](https://user-images.githubusercontent.com/11316335/98631449-162e8480-22e3-11eb-8781-33f42f3c76bc.png)

and identifying the largestcomponents:

![image](https://user-images.githubusercontent.com/11316335/98631476-23e40a00-22e3-11eb-97a0-3e02c5cceb2e.png)

The problem here is that both groups share "S", the correct results should be 1 - CH3S and 1 - CH3. The function identify twice the same group, where only one S is available. 

I would be very grateful if you can provide me more insight about this.

Thanks 
Kelvyn

**Comment by mojaie** [comment]
I'm sorry for late response.
This seems to be same as #31.
Your task is a kind of graph matching but this library does not offer it yet.
