### ISSUE TITLE
Add a few more topics?

### ISSUE THREAD

**Issue by timholy** [mojaie/MolecularGraph.jl#36]
I'm starting some cheminformatics work (I'm a newcomer to the field), and I was very excited to discover this package. It turns out to be harder to discover this package than it should be, and mostly this is not your fault: see https://github.com/JuliaComputing/JuliaHub/issues/81. But I wonder if it might be worth making it a little easier by adding a couple more topics? For example, "chemistry" seems like it might be a good addition to be sure that a "chemistry" [package search on JuliaHub](https://juliahub.com/ui/Packages) finds it.

Since you've already added a couple of tags, you presumably know this, but in case you forget it's described [here](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/classifying-your-repository-with-topics).

**Comment by mojaie** [comment]
Thank you very much for reaching out.
Surprisingly I have forgotten adding the word.
I added some general keywords for accessibility. I hope it will work.

**Comment by timholy** [comment]
That looks great, I'm sure it will help. JuliaHub probably updates their database at intervals, so it hasn't hit yet, but I'm sure it will help a lot. I think this can be closed.
