### ISSUE TITLE
Format of return from `edgesubgraphmatches`?

### ISSUE THREAD

**Issue by timholy** [mojaie/MolecularGraph.jl#39]
I'm trying to understand the format of the value returned by `edgesubgraphmatches`. I'm running a query where `length((query::QueryMol).nodeattrs` has length 17, but here's the Dict I get back:
```julia
Dict(22 => 15,37 => 9,18 => 16,32 => 14,24 => 18,53 => 2,40 => 5,61 => 1,16 => 13,47 => 20,11 => 12,21 => 17,13 => 8,25 => 19,29 => 4,27 => 10,19 => 6,15 => 11,12 => 7,30 => 3)
```
Why are the entries bigger than 17 in both of the first and second of the pairs?

**Comment by mojaie** [comment]
`edgesubgraphmatches` returns dict of matched "edge" pairs, so the numbers you mentioned are edge indices.
You can get the node mappings from a subgraph generated by 'edgesubgraph(mol, edges)'.

```julia
matches = iterate(edgesubgraphmatches(mol1, mol2))
subgraph1 = edgesubgraph(mol1, keys(matches))
subgraph2 = edgesubgraph(mol2, Set(values(matches)))
println(nodeset(subgraph1))
println(nodeset(subgraph2))
```

FYI: Reconstruction of subgraph match functions are ongoing  (see #33)
