### ISSUE TITLE
Any interest in 3d display?

### ISSUE THREAD

**Issue by timholy** [mojaie/MolecularGraph.jl#46]
Using Makie it's possible to create 3d plots:

```julia
julia> calotte(mol; H=false,markersize=2)
```
![image](https://user-images.githubusercontent.com/1525481/100864119-2e656f80-345b-11eb-90b0-ea4bb319907f.png)

(This would be improved by having a table of atomic radii.)

```julia
julia> ballstick(mol)
```
![image](https://user-images.githubusercontent.com/1525481/100864239-5a80f080-345b-11eb-861a-04725e4b4e6b.png)

If you're interested I could make a pull request. There are really three options wrt implementation:
- we could make Makie a hard dependency. That would likely have negative consequences for both load time and installability due to the requirement for OpenGL.
- we could put it inside a `@require Makie` block using [Requires](https://github.com/JuliaPackaging/Requires.jl)
- we could make it a separate package that depends on both MolecularGraph and Makie

I suspect the latter two are the best options. If you're interested, which do you prefer? One concern about the Requires approach is that it's not currently compatible with precompilation, but putting it in a separate package would allow that. Makie itself is not very well precompilable now, so at present it wouldn't really make any difference, but hopefully Makie will get more precompilable over time.

CC @SimonDanisch

**Comment by SimonDanisch** [comment]
There are also other projects for plotting molecules, which already have a dependency on Makie: 
https://github.com/ffreyer/LatPhysPlottingMakie.jl
https://github.com/kool7d/BioMakie.jl

You can also make a hard dependency on AbstractPlotting, which will allow the user to switch backends!

**Comment by mojaie** [comment]
Thank you very much! It looks really exciting.
If the basic 3D display can be simply implemented by using Makie or AbstractPlotting, I prefer using `@require`.
More specialized and larger codes unrelated to molecular graph model should be in separate packages.
I would be happy if you could add the functionality.

**Comment by timholy** [comment]
OK, see #47. I added an atom radius table, picking the [covalent radius](https://en.wikipedia.org/wiki/Covalent_radius) rather than [van der Waals radius](https://en.wikipedia.org/wiki/Van_der_Waals_radius) in part because I could find nearly-comprehensive tables for covalent radii but not for VdW radii. That means that my `spacefilling` function is not really space-filling in the usual sense; compare https://en.wikipedia.org/wiki/File:Thc.pdb.gif with

![image](https://user-images.githubusercontent.com/1525481/101008272-486c8400-3527-11eb-94fe-40eaaadb9f8b.png)

**Comment by timholy** [comment]
@SimonDanisch, I tried setting `strokecolor=nothing` to see if I could prevent it from drawing the surface of each of the spheres in black, but that was not effective. Any ideas?

**Comment by SimonDanisch** [comment]
I'd use meshscatter in this case ;) If you want them to look flat, you can set `shading=false`!

**Comment by timholy** [comment]
I like `meshscatter`. Interesting: `scatter` interprets `markersize` as a diameter, but `meshscatter` interprets it as a radius.

**Comment by timholy** [comment]
For comparison:

![image](https://user-images.githubusercontent.com/1525481/101016833-e9ab0880-352e-11eb-99cc-34029ebb65f1.png)
