### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by timholy** [mojaie/MolecularGraph.jl#51]
Would it be possible to get a new release of this package?

**Comment by mojaie** [comment]
Sure. I will submit v0.8.0 release.
Thank you again for your great contributions.

**Comment by mojaie** [comment]
Merged https://github.com/JuliaRegistries/General/pull/28977

**Comment by timholy** [comment]
Thanks so much!

For the TagBot issue https://github.com/mojaie/MolecularGraph.jl/issues/52#issuecomment-770175141, I can't help directly due to permissions, but https://github.com/julia-actions/MassInstallAction.jl/blob/dec8ce995d707b0008c0b1e47f93f7bcbad2d877/demos/MaintenanceDec2020/maintenance.jl#L24-L52 may make it easier. You can `add MassInstallAction`, then navigate to the demo direction, activate the Project.toml (either `Pkg.activate(".")` or on linux start Julia with `julia --project` from that directory), do lines like at the top of that script

```julia
using GitHub, MassInstallAction
import HTTP
# authenticate
auth = authenticate(#= your-github-personal-access-token =#)   # don't ever post this publicly!
rs = [repo(Repo("mojaie/MolecularGraph.jl"); auth=auth)]
```

and the you should be able to copy/paste any section of that script you want and have it make changes here.

**Comment by mojaie** [comment]
Thank you very much!
`MassInstallAction` pull requests were merged. I hope it works well.
