### ISSUE TITLE
V3000 format

### ISSUE THREAD

**Issue by hhaensel** [mojaie/MolecularGraph.jl#60]
Are there any plans to support the V3000 format?

**Comment by mojaie** [comment]
Thank you for your interest.
This library is mainly focused on handling molecular graphs, so the implementation of the input/output formats is not a high priority.
I look forward to further development of I/O libraries such as [Chemfiles.jl](https://github.com/chemfiles/Chemfiles.jl)

**Comment by hhaensel** [comment]
I leave it open until I have added radical support.
@mojaie if you want to do it, feel free, I'm currently busy with other things. It shouldn't be too difficult.

**Comment by hhaensel** [comment]
I studied your code on what you do with the `RAD` property and found that you store the value in multi. I've not understood what multi is used for, except that H atoms are displayed in the end.
@mojaie is radical support still under construction? And should I also store the `RAD` in multi? Would be a oneliner...

**Comment by mojaie** [comment]
`Atom.multiplicity` is intended to store radical information

Multiplicity  
https://en.wikipedia.org/wiki/Multiplicity_(chemistry)

so, mulitiplicity=1 usually means ground state, 2 means radical and 3 means biradical.

The specification for radical notation is not yet finalized.I would be happy if you let me know what you want to do with radicals and what specification is required in your usage. 

Drawing radical symbols in 2D images seems to be more difficult than expected. We need better positioning algorithm for it (#25 is an example of work around).

**Comment by hhaensel** [comment]
I currently don't have any need for radical support. I just thought, I'd try to bring the V3000 import to a similar state as the normal mol file format.

**Comment by mojaie** [comment]
Now supports v3000 readers (v3 .mol, .sdf, .rd and .rxn files)    cf3f890c79f99c7ab9f5e31c6059920f3357228c
