### ISSUE TITLE
Integrating MolecularGraph.jl with Gtk

### ISSUE THREAD

**Issue by Leticia-maria** [mojaie/MolecularGraph.jl#65]
Hello, I have written a code merging Gtk and MolecularGraph, creating a Graphical Interface to show the molecules. What do you think about implement it on this repository?

**Comment by mojaie** [comment]
I'm sorry for the late response.
Gtk integration seems to be great!

Here is structure drawing interface modules
https://github.com/mojaie/MolecularGraph.jl/tree/master/src/draw

draw2d.jl  is the interface, and svg.jl is an example of draw module implementation.

RDKit implementation of Cairo canvas would be helpful.
https://github.com/rdkit/rdkit/blob/b208da471f8edc88e07c77ed7d7868649ac75100/rdkit/Chem/Draw/cairoCanvas.py

**Comment by mojaie** [comment]
FYI: If you need just interactive drawing and rendering, Qt is also an option.
https://github.com/barche/QML.jl
I might have written Qt canvas for molecular drawing a long time ago. I would dig it up.
