### ISSUE TITLE
atomcount?

### ISSUE THREAD

**Issue by longemen3000** [mojaie/MolecularGraph.jl#7]
the amount of atoms is useful when calculating theoretical ideal gas Cp and Cv. any idea on how to extract this value on a molecular graph?

**Comment by mojaie** [comment]
`nodecount` will do that.

```julia
nodecount(mol)
```

I thought `atomcount` and `bondcount` were available as aliases of  `nodecount` and `edgecount` respectively but they were not. I will add them in next version. Thank you very much.
