### ISSUE TITLE
RDKit GetMolFrags equivalent?

### ISSUE THREAD

**Issue by longemen3000** [mojaie/MolecularGraph.jl#73]
hi, i'm trying to use this library to implement an UNIFAC group fragmenter (based on https://github.com/simonmb/fragmentation_algorithm/blob/master/fragmenter.py). looking at the code, the only function to do so that i couldn't find in this library  (and not depend on RDKit) is `rdkit.Chem.GetMolFrags` https://www.rdkit.org/docs/source/rdkit.Chem.rdmolops.html . Does MolecularGraph have some equivalent method?

**Comment by mojaie** [comment]
Thank you for your comment.
I guess `MolecularGraph.Graph.connectedcomponents` is what you want.

```
using MolecularGraph
using MolecularGraph.Graph

mol = smilestomol("CC(=O)[O-].[NH3+]C")
mol = removehydrogens(mol)
connectedcomponents(mol)
```

output:

```
2-element Vector{Set{Int64}}:
 Set([5, 6])
 Set([4, 2, 3, 1])
```

There are more graph topology-related functions in `MolecularGraph.Graph`
https://github.com/mojaie/MolecularGraph.jl/tree/master/src/graph
