### ISSUE TITLE
How does one go about generating the 3D visualization?

### ISSUE THREAD

**Issue by DoktorMike** [mojaie/MolecularGraph.jl#74]
In the Readme I can see the 3D structure listed and illustrated but I cannot for the life of me figure out how to do that? Am I missing something or has this feature been removed?

**Comment by mojaie** [comment]
Thank you for your question. Unfortunately it is still not documented yet.

Please refer:
[Add covalent radii and 3d drawing utilities](https://github.com/mojaie/MolecularGraph.jl/pull/47/files#)
[Any interest in 3d display?](https://github.com/mojaie/MolecularGraph.jl/issues/46#)

`spacefilling(mol)` or `ballstick(mol)` may work.
Optional dependency https://github.com/JuliaPlots/AbstractPlotting.jl should be installed. (This is no longer actively maintained and should be replaced by Makie.jl)
