### ISSUE TITLE
Make GraphMol extend AbstractGraph?

### ISSUE THREAD

**Issue by eahenle** [mojaie/MolecularGraph.jl#79]
The functionality throughout the JuliaGraphs ecosystem is quite robust.  It would be awesome if MolecularGraph were part of it.  This would allow directly plugging GraphMol objects into workflows built for other graph types, without first having to restructure the GraphMol to MetaGraph.

**Comment by mojaie** [comment]
I had the idea of making it a common interface with general graph modules like LightGraphs.jl previously, but I did not now how stable the development would be, so It was suspended. I would like to consider to do so if there is always common interface of graph model. Thank you for your suggestion!

You can see `PlainGraph` in the src/graph/plaingraph.jl, This is a mock(?) object of common graph interface and is used for many unit tests of simple graph operations that are not related to molecule properties.

**Comment by mojaie** [comment]
moved to #81
