### ISSUE TITLE
More properties?

### ISSUE THREAD

**Issue by SeanXiaoyuSun** [mojaie/MolecularGraph.jl#8]
Hi,

This MolecularGrpah.jl looks like a great substitution for RDKit.chem python package in Julia. However, some of molecular properties I was looking for seems to be missing right now, including:

- Atom properties:  number of radical electrons; Hybridization; Chirality 
- Bond property: Is conjugated or not

I think it might be worth to add these properties. Or were they already encoded and I just missed them?
Also, are there any ways to get 3d coords of atoms in a mol object and calculate the distance between every two atoms in that mol object?

**Comment by mojaie** [comment]
Thank you for reaching out to the repository.

`Atom` types have `multiplicity` field for radicals (Int type, 1: singlet, 2: doublet(radical), 3: triplet (biradical)), and SDFile parser may parse the radical state correctly. But still any calculation methods does not consider radicals.

You can get number of pi electrons of all atoms by `pielectron(mol)` method. I don't know how RDKit defines hybridization, but it may be not so difficult task... Please tell me your use case, if possible.

SMILES and SDFile parser can deal with chirality flag (`Atom.stereo` and `Bond.notation`). Molecular structure drawing considers chirality of molecules built from SDFile. Maybe CIP rule and absolute chirality notation will be implemented in the future for further analysis.

Conjugated bonds can be also known by `pielectron(mol)`.

3D coords are stored in `Atom.coords` if optimized 3D coords are described in SDFile. If not so, we need some molecular mechanics methods to determine 3D coords. It should be out of scope of this library. 

Any way we need documents and API references. I`m working on it...

**Comment by SeanXiaoyuSun** [comment]
Thank you for your very detailed response. Yeah documents and API would be very helpful.

Sorry I forgot to specify that I'm dealing with SMILES strings. Given that, I'm still confused about the chirality flag you mentioned. It seems that `SmilesAtom.stereo` and `SmilesBond.cistrans` (I assume this is the chirality flag for smiles mol?) will always be initialized with nothing. 
```
mol = smilestomol("C1CC(=O)NC(=O)C1N2C(=O)C3=CC=CC=C3C2=O")  # thalidomide, a molecule with chirality
for i in 1:nodecount(mol)
    println("atom: ",mol.nodeattrs[i].stereo)   # always prints nothing
    println("bond: ", mol.edgeattrs[i].cistrans)  # always prints nothing
end
```
What I want to get from "chirality" here is to get boolean result for each atom's chirality and each bond's stereo type (RDKit definition [here](https://www.rdkit.org/docs/cppapi/classRDKit_1_1Bond.html#ae91dd8e72b495a48f46775c874882165)). Any ways I can do it in this package?

About hybridization, [here](https://www.rdkit.org/docs/cppapi/classRDKit_1_1Atom.html#a58e40e30db6b42826243163175cac976) is RDKit's definition. Again, what I want is each atom's hybridization type from a mol obj. Is this encoded in this package?

 I noticed that SDFileAtom does have coords but SmilesAtom doesn't. Any ways I can get it for Smiles atoms?

Thanks

**Comment by mojaie** [comment]
Your code will return empty arrays because the SMILES string have no explicit chirality information (ex. C@@H or C\C=C/C). Chirality check is not implemented yet.

In most cases, pielectron=0 -> sp3, pielectron=1 -> sp2 and pielectron=2 -> sp. Other orbitals (s, sp3d and spd3d2) are special cases for specific atoms.

I'm working on 2D/3D coords generation now, but it would be offered as external libraries (see #3).

**Comment by SeanXiaoyuSun** [comment]
closing this issue since basically all questions were solved for now. Thanks!
