### ISSUE TITLE
MolecularGraph.Graph -> Graphs.jl

### ISSUE THREAD

**Issue by mojaie** [mojaie/MolecularGraph.jl#81]
See #79

Common graph theory functionalities (not specialized for molecular mining) in MolecularGraph.jl have been developed as a separate module `MolecularGraph.Graph` to someday be replaced by a more common and well-established graph library.

I found Graphs.jl has been stably and continuously developed, so I would like to move to that gradually.

**Comment by mojaie** [comment]
I'm working on this at `new_graphs` branch.
It may include many changes in concepts and code designs, and breaking changes in API are unavoidable in the next release.
I will also prepare new tutorials for that.

**Comment by Boxylmer** [comment]
Just to confirm, would the breaking changes be limited to functions contained within `MolecularGraph.Graph`? Or is any function fair game?

**Comment by mojaie** [comment]
For now,
- `MolecularGraph.Graph` would be removed, and some graph-related functions specific to molecular mining would be moved to `MolecularGraph` main module.
- Molecular graph types (e.g. GraphMol) are completely re-implemented using SimpleGraph, and may have interfaces similar to `MetaGraphs.jl`. This means the data previously generated by using older version of MolecularGraph.jl will not work at the next version.
- Many API functions would be renamed, but old names would be retained in several future versions. Some changes are to follow Graphs.jl ecosystem convention, and others are just for readability and convenience.
- I try to avoid structural changes to the API as much as possible, but if it does change, I would document or make tutorial.

**Comment by Boxylmer** [comment]
Fantastic! Very excited to see what performance and usability benefits the switch yields.

**Comment by mojaie** [comment]
Updates:

- Removed AbstractPlotting from optional dependencies, and added MakieCore instead. 3D molecule drawing would be provided as a Makie plot recipe.
- Added GeometryBasics as a dependency. MolecularGraph.Geometry may be replaced by it.
- Added Colors as a dependency for molecule drawing.

**Comment by mojaie** [comment]
This was merged to `master` branch
