### ISSUE TITLE
Update and expand 3D display functions?

### ISSUE THREAD

**Issue by tmcgrath325** [mojaie/MolecularGraph.jl#88]
Related: #74, #46

Since AbstractPlotting.jl is no longer supported, it seems like a good idea to update the 3D display to require Makie.jl instead. It also might be nice to be able to have some additional plotting options, like the [stick and wire-frame displays here](https://pubchem.ncbi.nlm.nih.gov/compound/Aspirin#section=3D-Conformer). 

I've started to implement these while keeping the existing interface mostly intact:

```julia
julia> using GLMakie, MolecularGraph

julia> mol = sdftomol("assets/test/aspirin_3d.sdf")

julia> ballstick(mol)
```
![ballstick](https://user-images.githubusercontent.com/72618709/229389942-24b89c46-aed1-45cc-83ef-bcca6f54f0d3.png)

I also wanted to add the option for a "stick" display...

```julia
julia> stick(mol)
```
![stick](https://user-images.githubusercontent.com/72618709/229390258-a6c433d8-ebbc-4dad-a19c-6d9c346bcc33.png)

...as well as a way to easily plot multiple molecules in a single figure:

```julia
julia> tforms = [x -> [x[1] + (i-1)*10, x[2], x[3]] for i=1:4];

julia> fig = stick(mol; tform=tforms[1])

julia> ax = fig.content[1];

julia> ballstick!(ax, mol; tform=tforms[2]);

julia> spacefilling!(ax, mol; tform=tforms[3]);

julia> wire!(ax, mol; tform=tforms[4]);
```
![draw3d](https://user-images.githubusercontent.com/72618709/229389575-52b82c2b-f91c-426f-a364-45d71f8bebfd.png)

Would you be interested in making these kinds of changes to the 3D display implementation? If so, I can put together a pull request with the work I've done so far.

**Comment by mojaie** [comment]
Thank you for the great idea!
I'm already working on Makie interface (see `new_graph` and 'dev' branch)
Could you wait for the branch is merged to main branch?

**Comment by DoktorMike** [comment]
As the dev branch is merged now, would it make sense to address this? I think this would indeed be a cool addition to this project. :)

**Comment by tmcgrath325** [comment]
Since @mojaie indicated that contributions to 3D drawing are welcome in #89, I made a pull request with some additional features (see #90).

New additions include the "stick" and "wire" plots shown above. I've also tried to make it easy to combine multiple molecules or display types:

```julia
julia> using GLMakie, MolecularGraph

julia> mol = sdftomol("assets/test/aspirin_3d.sdf");

julia> f = wire(mol); spacefilling!(mol, alpha=0.2); f
```

![combined](https://user-images.githubusercontent.com/72618709/232561824-3797bab5-643b-45d1-9c98-4e3b91f954ed.png)

**Comment by mojaie** [comment]
Thank you very much, it looks great!
I could reproduce with also WGLMakie
![スクリーンショット 2023-04-18 11 32 12](https://user-images.githubusercontent.com/1174134/232655204-45930d15-7a43-44ff-ba07-3ac478fe5ca2.png)
