### ISSUE TITLE
name clash with Base.VERSION

### ISSUE THREAD

**Issue by hhaensel** [mojaie/MolecularGraph.jl#92]
The latest version has a problem with exporting `VERSION`.
Any usage of `VERSION` after loading MolecularGraph will fail.

My recommendation would be to either export MG_VERSION or don't export it at all (favoured).
If people want to refer to a version number of MolecularGraph, it feels quite normal to call MolecularGraph.VERSION

**Comment by mojaie** [comment]
Thank you for catching that.
MolecularGraph.VERSION looks better so I will simply remove the export.

**Comment by hhaensel** [comment]
Pleasure to help. It's such an excellent package!

BTW, are you interested in getting the lines of your drawings completely connected?

**Comment by mojaie** [comment]
What does "completely connected" mean?
Improvements in the quality of molecule drawings are always welcome. Could you make a separate issue about it?
