### ISSUE TITLE
Coulomb matrices calculation

### ISSUE THREAD

**Issue by DoktorMike** [mojaie/MolecularGraph.jl#99]
I was recently looking into Coulomb matrices and their calculation. I was wondering if such a thing is within the scope of this package? It requires inter-atom distances in, I would assume, 3D. After that the calculation is done per conformer. So to do this we would have to:

1. Go from SMILES to 3D coordinates
2. Get the charges for each atom
3. Generate a set of conformers for each molecule

Currently I think we are lacking 1 and 3. Step 1 could be done by reading SDF files instead of SMILES I would presume.

**Comment by mojaie** [comment]
Thank you very much. I'm not sure but
1 and 3 maybe requires force fields like MMFF. One of opensource implementation is included in RDKit under BSD license. 
https://jcheminf.biomedcentral.com/articles/10.1186/s13321-014-0037-3
For now I prefer molecular mechanics/dynamics would be provided as separate package, and MolecularGraph.jl should provide compatible interfaces for them.

**Comment by DoktorMike** [comment]
> Thank you very much. I'm not sure but 1 and 3 maybe requires force fields like MMFF. One of opensource implementation is included in RDKit under BSD license. https://jcheminf.biomedcentral.com/articles/10.1186/s13321-014-0037-3 For now I prefer molecular mechanics/dynamics would be provided as separate package, and MolecularGraph.jl should provide compatible interfaces for them.

Thanks for the clarification. If I manage to implement the coulomb matrices I'll look into interfacing with this project. :) I'll close this for now.
